version: "3.7"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432

  api-pass-in:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - 3001:3333
    environment:
      - DATABASE_URL=file:./db.sqlite
      - API_BASE_URL=http://localhost:3333
